# Generated by Django 6.0.2 on 2026-02-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_roll_no_student_rollno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.AddField(
            model_name='student',
            name='face_video',
            field=models.FileField(default='temp.mp4', upload_to='student_videos/'),
            preserve_default=False,
        ),
    ]
