# Generated by Django 6.0.2 on 2026-02-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_student_image_student_face_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
