# Generated by Django 6.0.2 on 2026-03-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_face_encoding'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='Present', max_length=20),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='session',
        ),
    ]
