# Generated by Django 6.0.2 on 2026-04-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_attendance_unique_together_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(default='General Class', max_length=50),
        ),
    ]
