# Generated by Django 6.0.2 on 2026-04-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_classroom_remove_student_class_name_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='123456', max_length=50),
        ),
    ]
